---

- name: Download Jenkins repository
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: '0622'

- name: Import Jenkins GPG key 
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-{{ jenkins_gpg_key_year }}.key

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Upgrade Jenkins
  ansible.builtin.yum:
    name: jenkins
    state: latest